CREATE TABLE FAHRZEUG
(
    FAHRZEUGKENNZEICHEN VARCHAR(40) PRIMARY KEY,
    BAUJAHR DATE,
    ZULÄSSIGES_GESAMTGEWICHT DECIMAL(18,2),
    FUNKKENNUNG VARCHAR(40)
);

CREATE TABLE STRAßENWART
(
    STRAßENWART_ID INT PRIMARY KEY AUTO_INCREMENT,
    VORNAME VARCHAR(40),
    NACHNAME VARCHAR(20),
    MOBILFUNKNUMMER VARCHAR(10)
);

CREATE TABLE AUTOBAHNABSCHNITT
(
    AUTOBAHNABSCHNITT_ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTOBAHNNUMMER VARCHAR(40),
    AUTOBAHNKILOMETERSTART DECIMAL(18,2),
    AUTOBAHNKILOMETERENDE DECIMAL(18,2),
    REIHENFOLGE INT
);

CREATE TABLE EINSATZPLAN
(
    EINSATZPLAN_ID INT PRIMARY KEY AUTO_INCREMENT,
    WOCHENTAG VARCHAR(40),
    TAGESZEIT VARCHAR(20),
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);

CREATE TABLE RÄUMSTREUFAHRZEUG
(
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    RÄUMBREITE DECIMAL(18,2),
    SALZKAPAZITÄT DECIMAL(18,2),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);

CREATE TABLE SCHNEEFRÄSEN
(
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);

CREATE TABLE SCHNEESCHLEUDER
(
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);


CREATE TABLE STRAßENWART_FAHRZEUGKLASSE
(
    STRAßENWART_ID INT,
    FAHRZEUGKLASSE VARCHAR(40),
    FOREIGN KEY (STRAßENWART_ID) REFERENCES STRAßENWART(STRAßENWART_ID)
);

CREATE TABLE EINSATZPLAN_AUTOBAHNABSCHNITT
(
    EINSATZPLAN_ID VARCHAR(40),
    AUTOBAHNABSCHNITT_ID INT,
    FOREIGN KEY (EINSATZPLAN_ID) REFERENCES EINSATZPLAN(EINSATZPLAN_ID),
    FOREIGN KEY (AUTOBAHNABSCHNITT_ID) REFERENCES AUTOBAHNABSCHNITT(AUTOBAHNABSCHNITT_ID)
);

CREATE TABLE EINSATZPLAN_STRAßENWART
(
    EINSATZPLAN_ID VARCHAR(40),
    STRAßENWART_ID INT,
    FOREIGN KEY (EINSATZPLAN_ID) REFERENCES EINSATZPLAN(EINSATZPLAN_ID),
    FOREIGN KEY (STRAßENWART_ID) REFERENCES STRAßENWART(STRAßENWART_ID)
);


insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULÄSSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('SCFEBBAK8BG989852', PARSEDATETIME('15.07.2021','dd.MM.yyyy'), 70.44, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULÄSSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('1D7RW2BK3BS301715', PARSEDATETIME('08.09.2021','dd.MM.yyyy'), 66.62, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULÄSSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('5GADT13S772781367', PARSEDATETIME('04.02.2021','dd.MM.yyyy'), 71.02, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULÄSSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('WAUAFAFL7DN381216', PARSEDATETIME('14.09.2021','dd.MM.yyyy'), 44.62, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULÄSSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('SCFEBBCF1CG694710', PARSEDATETIME('21.07.2021','dd.MM.yyyy'), 70.97, null);
insert into  SCHNEEFRÄSEN (FAHRZEUGKENNZEICHEN) values ('SCFEBBAK8BG989852');
insert into  SCHNEESCHLEUDER (FAHRZEUGKENNZEICHEN) values ('1D7RW2BK3BS301715');
insert into  SCHNEEFRÄSEN (FAHRZEUGKENNZEICHEN) values ('5GADT13S772781367');
insert into  SCHNEESCHLEUDER (FAHRZEUGKENNZEICHEN) values ('WAUAFAFL7DN381216');
insert into  RÄUMSTREUFAHRZEUG (FAHRZEUGKENNZEICHEN,RÄUMBREITE,SALZKAPAZITÄT) values ('WAUAFAFL7DN381216', 20.1, 20.2);
insert into  STRAßENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Dynah', 'Orrom', '9028075902');
insert into  STRAßENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Valentina', 'Petrecz', '3016184350');
insert into  STRAßENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Mandie', 'Grombridge', '2462060117');
insert into  STRAßENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Nessa', 'Lidgett', '5955649733');
insert into  STRAßENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Georgianna', 'Whickman', '3123794218');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(1,'Schneefräsen');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(1,'Schneeschleuder');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(2,'Schneeschleuder');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(2,'Räumstreufahrzeug');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(3,'Schneefräsen');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(3,'Schneeschleuder');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(3,'Räumstreufahrzeug');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(4,'Schneeschleuder');
insert into  STRAßENWART_FAHRZEUGKLASSE(STRAßENWART_ID,FAHRZEUGKLASSE) values(5,'Schneefräsen');
