CREATE TABLE FAHRZEUG
(
    FAHRZEUGKENNZEICHEN VARCHAR(40) PRIMARY KEY,
    BAUJAHR DATE,
    ZULAESSIGES_GESAMTGEWICHT DECIMAL(18,2),
    FUNKKENNUNG VARCHAR(40)
);

CREATE TABLE STRASSENWART
(
    STRASSENWART_ID INT PRIMARY KEY AUTO_INCREMENT,
    VORNAME VARCHAR(40),
    NACHNAME VARCHAR(20),
    MOBILFUNKNUMMER VARCHAR(10)
);

CREATE TABLE AUTOBAHNABSCHNITT
(
    AUTOBAHNABSCHNITT_ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTOBAHNNUMMER VARCHAR(40),
    AUTOBAHNKILOMETERSTART DECIMAL(18,2),
    AUTOBAHNKILOMETERENDE DECIMAL(18,2),
    REIHENFOLGE INT
);

CREATE TABLE EINSATZPLAN
(
    EINSATZPLAN_ID INT PRIMARY KEY AUTO_INCREMENT,
    WOCHENTAG VARCHAR(40),
    TAGESZEIT VARCHAR(20),
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    STRASSENWART_ID_1 INT,
    STRASSENWART_ID_2 INT,
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN),
    FOREIGN KEY (STRASSENWART_ID_1) REFERENCES STRASSENWART(STRASSENWART_ID),
    FOREIGN KEY (STRASSENWART_ID_2) REFERENCES STRASSENWART(STRASSENWART_ID)
);

CREATE TABLE RAEUMSTREUFAHRZEUG
(
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    RAEUMBREITE DECIMAL(18,2),
    SALZKAPAZITAET DECIMAL(18,2),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);

CREATE TABLE SCHNEEFRAESEN
(
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);

CREATE TABLE SCHNEESCHLEUDER
(
    FAHRZEUGKENNZEICHEN VARCHAR(40),
    FOREIGN KEY (FAHRZEUGKENNZEICHEN) REFERENCES FAHRZEUG(FAHRZEUGKENNZEICHEN)
);


CREATE TABLE STRASSENWART_FAHRZEUGKLASSE
(
    STRASSENWART_ID INT,
    FAHRZEUGKLASSE VARCHAR(40),
    FOREIGN KEY (STRASSENWART_ID) REFERENCES STRASSENWART(STRASSENWART_ID)
);

CREATE TABLE EINSATZPLAN_AUTOBAHNABSCHNITT
(
    EINSATZPLAN_ID VARCHAR(40),
    AUTOBAHNABSCHNITT_ID INT,
    FOREIGN KEY (EINSATZPLAN_ID) REFERENCES EINSATZPLAN(EINSATZPLAN_ID),
    FOREIGN KEY (AUTOBAHNABSCHNITT_ID) REFERENCES AUTOBAHNABSCHNITT(AUTOBAHNABSCHNITT_ID)
);


insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULAESSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('SCFEBBAK8BG989852', PARSEDATETIME('15.07.2021','dd.MM.yyyy'), 70.44, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULAESSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('1D7RW2BK3BS301715', PARSEDATETIME('08.09.2021','dd.MM.yyyy'), 66.62, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULAESSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('5GADT13S772781367', PARSEDATETIME('04.02.2021','dd.MM.yyyy'), 71.02, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULAESSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('WAUAFAFL7DN381216', PARSEDATETIME('14.09.2021','dd.MM.yyyy'), 44.62, null);
insert into  FAHRZEUG (FAHRZEUGKENNZEICHEN, BAUJAHR, ZULAESSIGES_GESAMTGEWICHT, FUNKKENNUNG) values ('SCFEBBCF1CG694710', PARSEDATETIME('21.07.2021','dd.MM.yyyy'), 70.97, null);
insert into  SCHNEEFRAESEN (FAHRZEUGKENNZEICHEN) values ('SCFEBBAK8BG989852');
insert into  SCHNEESCHLEUDER (FAHRZEUGKENNZEICHEN) values ('1D7RW2BK3BS301715');
insert into  SCHNEEFRAESEN (FAHRZEUGKENNZEICHEN) values ('5GADT13S772781367');
insert into  SCHNEESCHLEUDER (FAHRZEUGKENNZEICHEN) values ('WAUAFAFL7DN381216');
insert into  RAEUMSTREUFAHRZEUG (FAHRZEUGKENNZEICHEN,RAEUMBREITE,SALZKAPAZITAET) values ('WAUAFAFL7DN381216', 20.1, 20.2);
INSERT INTO STRASSENWART (STRASSENWART_ID ) VALUES(0)
insert into  STRASSENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Dynah', 'Orrom', '9028075902');
insert into  STRASSENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Valentina', 'Petrecz', '3016184350');
insert into  STRASSENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Mandie', 'Grombridge', '2462060117');
insert into  STRASSENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Nessa', 'Lidgett', '5955649733');
insert into  STRASSENWART (VORNAME, NACHNAME, MOBILFUNKNUMMER) values ('Georgianna', 'Whickman', '3123794218');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(1,'Schneefraesen');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(1,'Schneeschleuder');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(2,'Schneeschleuder');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(2,'Raeumstreufahrzeug');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(3,'Schneefraesen');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(3,'Schneeschleuder');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(3,'Raeumstreufahrzeug');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(4,'Schneeschleuder');
insert into  STRASSENWART_FAHRZEUGKLASSE(STRASSENWART_ID,FAHRZEUGKLASSE) values(5,'Schneefraesen');

INSERT INTO EINSATZPLAN(WOCHENTAG,TAGESZEIT,FAHRZEUGKENNZEICHEN,STRASSENWART_ID_1,STRASSENWART_ID_2)
VALUES('MONTAG','TAGSUEBER','SCFEBBAK8BG989852',1,2);

INSERT INTO AUTOBAHNABSCHNITT (AUTOBAHNNUMMER,AUTOBAHNKILOMETERSTART,AUTOBAHNKILOMETERENDE,REIHENFOLGE)
VALUES('A23',10,20,1);
INSERT INTO AUTOBAHNABSCHNITT (AUTOBAHNNUMMER,AUTOBAHNKILOMETERSTART,AUTOBAHNKILOMETERENDE,REIHENFOLGE)
VALUES('A23',24,45,2);
INSERT INTO EINSATZPLAN_AUTOBAHNABSCHNITT (EINSATZPLAN_ID,AUTOBAHNABSCHNITT_ID )
VALUES(1,1);
INSERT INTO EINSATZPLAN_AUTOBAHNABSCHNITT (EINSATZPLAN_ID,AUTOBAHNABSCHNITT_ID )
VALUES(1,2);
